### ISSUE TITLE
Methods Plugin - Data Gathering

### ISSUE THREAD

**Issue by tbrandirali** [tudorpopovici1/demo-plugin-jetbrains-project#6]
Implementing logic to walk currently open file from editor, find all methods and walk those method objects to gather statistics.
Statistics to implement:
* Total number of methods
* Total number of public methods
* Total number of private methods
* Public / private ratio
* (Optional) Maximum cyclomatic complexity

**Comment by tudorpopovici1** [comment]
Adding to the list:

- cyclomatic complexity per method
- LOC per method (lines of code)

**Comment by tbrandirali** [comment]
> 
> 
> Adding to the list:
> 
>     * cyclomatic complexity per method
> 
>     * LOC per method (lines of code)

Cyclomatic complexity is interesting, I'll see if it's doable to implement it within the deadline. LOC per method might be too much of a longshot though, because they are only defined outside of the Psi.
