### ISSUE TITLE
Markdown Plugin - Data Persistence

### ISSUE THREAD

**Issue by tbrandirali** [tudorpopovici1/demo-plugin-jetbrains-project#7]
Implement the PersistentStateComponent interface to store data between runs of the action.
Implement logic to compare data from current run with data from previous ones.

**Comment by tudorpopovici1** [comment]
We have managed to collect all of the planned statistics without implementing Data Persistence functionality for the Markdown Plugin. Of course, in the future, this could be added to improve user experience and add more advanced statistics. Closing the issue for now.
